//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedback.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FeedBackEntities : DbContext
    {
        public FeedBackEntities()
            : base("name=FeedBackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseInfo> CourseInfoes { get; set; }
        public virtual DbSet<FeedbackInfo> FeedbackInfoes { get; set; }
        public virtual DbSet<QuestionInfo> QuestionInfoes { get; set; }
        public virtual DbSet<RightInfo> RightInfoes { get; set; }
        public virtual DbSet<RoleAndRightsInfo> RoleAndRightsInfoes { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<TeacherCourseInfo> TeacherCourseInfoes { get; set; }
        public virtual DbSet<TeacherInfo> TeacherInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
